//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManagerDB.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int Id { get; set; }
        public string FacebookContact { get; set; }
        public string TwitterContact { get; set; }
        public string SkypeContact { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
